

name: Build and Testchmod +x gradlewchmod +x gradlew


on: 
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master ]
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'        
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
          
      
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run Tests
      run : ./gradlew  test
      
    - name: Run Unit-Tests
      run: chmod +x ./app/src/test/java/com/example/sweat4success/*

    - name: Build Project
      run: ./gradlew assemble
      
    - name: CodeCov report deploy
      run: bash <(curl -s https://codecov.io/bash)
      
    - name: Build and analyze sonarqube
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: ./gradlew build sonarqube --info 
